@startuml
title: Sign in

participant Mobile as Mob
participant "Push Gateway" as push
participant Backend as Back

autonumber
Mob -> Back: phone
Back -> Back: generate OTP
Back -> push: send OTP
push -> Mob: OTP
Mob -> Mob: Sign OTP with private key
Mob -> Back: Signed OTP
Back -> Back: Validate OTP with public key
Back -> Back: Generate JWT
Back -> Mob: JWT (scope: regular)
@enduml