@startuml
title: Signup

actor Client as user
participant Mobile as Mob
participant "SMS Gateway" as sms
participant "Push Gateway" as push
participant Backend as Back

autonumber
user -> Mob: phone, birthday
user -> Mob: passcode
Mob -> Back: SignUp (phone, birthday, passcode)

== SMS Validation ==
Back -> Back: Generate OTP
Back -> sms: Send OTP SMS
sms -> Mob: SMS with OTP
user -> Mob: OTP
Mob -> Back: OTP
Back -> Back: Validate OTP
Back -> Back: Generate JWT
Back -> Mob: JWT (scope: registration)

== Push Validation ==
Mob -> push: get push token
push -> Mob: push token
Mob -> Mob: Generate keys (public, private)
Mob -> Back: Push token and public key
Back -> Back: Create mobile device for user in DB
Back -> Back: Generate JWT
Back -> Mob: JWT (scope: regular)
@enduml